batch_size: 128
epochs: 20
eval_every_n_epochs: 1
fine_tune_from: ''
log_every_n_steps: 25
weight_decay: 10e-6
fp16_precision: False
n_gpu: 2
gpu_ids: (0,1)
out_dim: 512
log_dir: 'weights_clr'

dataset_name: 'colon'
dataset:
  s: 1
  input_shape: (256, 256, 3)
  num_workers: 10
  valid_size: 0.1
  data_path: "/path/to/data"

loss:
  temperature: 0.5
  use_cosine_similarity: True